print("What is your name?")
name = input("?")
print("What do you want your username to be?")
username = input("?")
print("What do you want your password:")
password = input("?")
print("Please re enter your password")
ReEnteredPassword = input("?")
print("Welcome " + username)
